# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  draft01api:
    image: draft01api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 5009:5009
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
